# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.film_manager:
        class: AppBundle\Services\FilmManager
        arguments: ['@doctrine.orm.entity_manager']

    app.news_manager:
        class: AppBundle\Services\NewsManager
        arguments: ['@doctrine.orm.entity_manager']